spring:
  datasource:
    url: jdbc:h2:mem:sfchain;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

sf-chain:
  authEnabled: false
  persistence:
    database-type: postgresql
  features:
    local-persistence: true
    local-migration: false
    management-api: true
    static-ui: true
